### ISSUE TITLE
Not working- how to debug?

### ISSUE THREAD

**Issue by chrisdel101** [Tyriar/vscode-lorem-ipsum#6]
I'm new to VScode and this is not working. I've installed/uninstalled. After installation nothing happens. I might be doing it wrong?

I'm on mac. Hitting `cmd-P` opens the bar and tying `lorem` there does nothing. Thanks for any help.

**Comment by Tyriar** [comment]
cmd+p lets you find files, cmd+shift+p open the command palette where it should be.
